### ISSUE TITLE
New release against thrift 0.13?

### ISSUE THREAD

**Issue by saethlin** [sunchao/parquet-format-rs#11]
Thrift 0.12 depends on `byteorder ~1.2`, which means the current release of this crate cannot be in the same dependency tree as `bincode ^1.0`, because that has a dependency on `byteorder ^1.3`.

This shouldn't be a problem again because `thrift` now has all caret dependencies, and all that's required here is to publish a new release that's the current version of master. It would mean a lot.

**Comment by sunchao** [comment]
@saethlin Created #12 for this.

**Comment by sunchao** [comment]
Released 2.6.1 with thrift 0.13 support.

**Comment by saethlin** [comment]
You're great. Thank you.
