### ISSUE TITLE
2.7.0 release was semver-breaking, and breaks parquet upon cargo-update

### ISSUE THREAD

**Issue by saethlin** [sunchao/parquet-format-rs#14]
I have an existing build that uses `parquet = "2.0"`. If I `cargo update -p parquet-format`: 
```rust
error[E0063]: missing fields `file_offset`, `ordinal`, `total_compressed_size` in initializer of `RowGroup`
   --> /home/ben/.cargo/registry/src/github.com-1ecc6299db9ec823/parquet-2.0.0/src/file/metadata.rs:262:9
    |
262 |         RowGroup {
    |         ^^^^^^^^ missing `file_offset`, `ordinal`, `total_compressed_size`

error[E0063]: missing field `bloom_filter_offset` in initializer of `ColumnMetaData`
   --> /home/ben/.cargo/registry/src/github.com-1ecc6299db9ec823/parquet-2.0.0/src/file/metadata.rs:485:31
    |
485 |         let column_metadata = ColumnMetaData {
    |                               ^^^^^^^^^^^^^^ missing `bloom_filter_offset`

error[E0063]: missing fields `crypto_metadata`, `encrypted_column_metadata` in initializer of `ColumnChunk`
   --> /home/ben/.cargo/registry/src/github.com-1ecc6299db9ec823/parquet-2.0.0/src/file/metadata.rs:501:9
    |
501 |         ColumnChunk {
    |         ^^^^^^^^^^^ missing `crypto_metadata`, `encrypted_column_metadata`

error[E0063]: missing fields `encryption_algorithm`, `footer_signing_key_metadata` in initializer of `parquet_format::FileMetaData`
   --> /home/ben/.cargo/registry/src/github.com-1ecc6299db9ec823/parquet-2.0.0/src/file/writer.rs:172:29
    |
172 |         let file_metadata = parquet::FileMetaData {
    |                             ^^^^^^^^^^^^^^^^^^^^^ missing `encryption_algorithm`, `footer_signing_key_metadata`

error: aborting due to 4 previous errors
```

**Comment by nevi-me** [comment]
Hi @saethlin. We apologise for the inconvenience.

This crate follows the https://github.com/apache/parquet-format/releases versioning, which isn't semver compatible.
So the likelihood of crates depending on `parquet-format-rs` breaking is high, for example parquet `2.7.0` adds encryption support, as you can see from errors.

May you please pin version `~2.6.1` on your crate(s).

**Comment by saethlin** [comment]
Ah. Your use of ~ requirements has resulted in build breaks for us in the past, which prompted forking Apache crates to fix them. I see now that this was not a mistake. We'll be looking to migrate off your code ASAP, sorry about the inconvenience.

**Comment by nevi-me** [comment]
Hey @saethlin, I don't quite follow.

> Your use of ~ requirements has resulted in build breaks for us in the past, which prompted forking Apache crates to fix them.

Are you referring to the `parquet` crate?

> We'll be looking to migrate off your code ASAP, sorry about the inconvenience.

No worries, it's no inconvenience. Out of interest, are you building an alternative parquet implementation? I'd only really expect users of this crate to be building a parquet implementation.

**Comment by saethlin** [comment]
> Are you referring to the parquet crate?

I may have been too liberal with my use of the word "Your". I think it was the `thrift` crate actually that had a ~ dependency on byteorder and was preventing us from adding a crate to our dependency tree.

> Out of interest, are you building an alternative parquet implementation?

No, we are/were users of the `parquet` crate. The build break happens through it, because it declares a dependency `parquet-format = "2.6.1"` which due to the implicit caret causes Cargo to select `parquet-format` 2.7.0.

**Comment by nevi-me** [comment]
Ah, that makes sense. The next `parquet` release is about 2 weeks away. We missed the change unpinning the dependency, but we'll fix it in the main branch soon.

Interestingly, the break happened when you helped us make some dependencies optional (https://github.com/apache/arrow/commit/2840e3f01be65676a511d7eb25b48e46e358ecef). We'll document why we pin the version, so that we don't break builds again.

**Comment by sunchao** [comment]
@saethlin sorry for the inconvenience! the problematic version (2.7.0) is yanked and the issue should be gone now.
