### ISSUE TITLE
Latest parquet-format 2.7.0 cause compile issue for parquet 2.0.0

### ISSUE THREAD

**Issue by Tranway1** [sunchao/parquet-format-rs#15]
error[E0063]: missing fields `file_offset`, `ordinal`, `total_compressed_size` in initializer of `parquet_format::parquet_format::RowGroup`
   --> /Users/.cargo/registry/src/github.com-1ecc6299db9ec823/parquet-2.0.0/src/file/metadata.rs:262:9
    |
262 |         RowGroup {
    |         ^^^^^^^^ missing `file_offset`, `ordinal`, `total_compressed_size`

error[E0063]: missing field `bloom_filter_offset` in initializer of `parquet_format::parquet_format::ColumnMetaData`
   --> /Users/.cargo/registry/src/github.com-1ecc6299db9ec823/parquet-2.0.0/src/file/metadata.rs:485:31
    |
485 |         let column_metadata = ColumnMetaData {
    |                               ^^^^^^^^^^^^^^ missing `bloom_filter_offset`

error[E0063]: missing fields `crypto_metadata`, `encrypted_column_metadata` in initializer of `parquet_format::parquet_format::ColumnChunk`
   --> /Users/.cargo/registry/src/github.com-1ecc6299db9ec823/parquet-2.0.0/src/file/metadata.rs:501:9
    |
501 |         ColumnChunk {
    |         ^^^^^^^^^^^ missing `crypto_metadata`, `encrypted_column_metadata`

error[E0063]: missing fields `encryption_algorithm`, `footer_signing_key_metadata` in initializer of `parquet_format::parquet_format::FileMetaData`
   --> /Users/.cargo/registry/src/github.com-1ecc6299db9ec823/parquet-2.0.0/src/file/writer.rs:172:29
    |
172 |         let file_metadata = parquet::FileMetaData {
    |                             ^^^^^^^^^^^^^^^^^^^^^ missing `encryption_algorithm`, `footer_signing_key_metadata`

error: aborting due to 4 previous errors

For more information about this error, try `rustc --explain E0063`.
error: could not compile `parquet`.

**Comment by sunchao** [comment]
Sorry for the inconvenience and please see similar issue in #14.

I think to fix this, we'll need to revert #8 and publish a new version (2.7.1) for this crate. After that we can restore the commit and bump the major version (3.0.0) & publish. 

This also means we'll abandon the policy that:
```
the version in Cargo.toml should match the Parquet format version of the parquet.thrift in apache/parquet-format.
```

IMO this is not a big issue. Instead we can have a mapping (parquet-format-rs version -> parquet-format version) in README.

@nevi-me what do you think?

**Comment by nevi-me** [comment]
@sunchao I'm fine with abandoning the policy, and yanking 2.7.0, which might be better than releasing 2.7.1. if that doesn't work, we can revert #8

**Comment by nevi-me** [comment]
I've yanked 2.7.0

**Comment by sunchao** [comment]
Oh cool. Thanks @nevi-me ! I think we should still bump the major version next time publishing the crate (which means abandoning the policy) so that parquet-2.0 won't be affected.

**Comment by nevi-me** [comment]
Yup, I'll release f2.7.0 as v3.0.0 today

**Comment by sunchao** [comment]
Closing this as version 2.7.0 is yanked - @Tranway1 let us know if you still see the issue.
